### PR TITLE
Add dependencies command

### PR DESCRIPTION
**Pull request by wfleming**
This adds a new command called `dependencies`, which will process entries in the `dependencies.files` key & download files.

cc @codeclimate/review this is mostly the same code, just tweaked a bit, but review would be appreciated!

### CODE REVIEW

**Comment by pbrisbin** [comment]
For the UX, I imagined it'd just be `codeclimate dependencies`, just because today it only has a `files` sub-key and only takes that action, I still see the command as broader and open to future extension. WDYT?

**Comment by pbrisbin** [comment]
`codeclimate dependencies --files` might be another options, if you really want to make the "I'm only doing `files` things" explicit.

**Comment by wfleming** [comment]
> For the UX, I imagined it'd just be codeclimate dependencies. Just because today it only has a files sub-key and only takes that action, I still see the command as broader and open to future extension. WDYT?

@pbrisbin I think we'd still want to be able to execute individual sub-parts of `dependencies` independently. Were you thinking a git-style `codeclimate dependencies files` for that case, and a plain `codeclimate dependencies` do (potentially) everything?

**Comment by pbrisbin** [comment]
Yes, I think `codeclimate dependencies` would do everything (which is today just the `files` stuff). Then if/when we extend further we can decide if:

- A sub-sub command makes sense (your suggestion)
- A flag makes sense (my second suggestin)
- It actually doesn't ever make sense to do "part" of the dependencies step (what I think is likely)

I don't see it backing us into anything, personally.

**Comment by wfleming** [comment]
@pbrisbin updated

**Comment by pbrisbin** [comment]
Cool, LGTM.

**Pull request merged**
