### PR TITLE
Order checks alphabetically

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Move Style section to end.
Add `Included Cops` comment listing headers for easy navigation.
Alphabetically order metrics section.

First step of [this pull](https://github.com/codeclimate/codeclimate/pull/283) updating default `.rubocop.yml` generated during `init`. 

@codeclimate/review @jpignata

### CODE REVIEW

**Comment by jpignata** [comment]
I don't understand the point of the "included cops" comment.

**Comment by jpignata** [comment]
Seems like there are some cops listed out of order in at least the metrics category.

**Comment by jpignata** [comment]
Since we're rearranging deck chairs here, I'd say the pre-existing comment that opens the file, specifically line 2, is also bunk. I'd nuke it.

Also lines 328 - 330. Seems self-explanatory.

I don't know what line 10 is trying to communicate.

**Comment by ABaldwinHunter** [comment]
@jpignata Thanks!

I agree on points, except I found the `included cops` or `headings` comment a nice overview (otherwise you'd have to scroll to see what sections were present). 

But I removed it for now.

**Comment by ABaldwinHunter** [comment]
Fixes in place. Leaving commits while in review but can `fixup` at end.

**Comment by jpignata** [comment]
Thanks. Since we're including all categories and all checks within all categories, this seemed redundant and I thought it was communicating something I was missing.

This looks good to me. I'd squash down into one commit but seems good to merge.

**Comment by ABaldwinHunter** [comment]
@jpignata Thanks, that makes sense. I hadn't realized the config was exhaustive.

`Fix`ed`up`.

**Pull request merged**
