### PR TITLE
Add pylint engine

### PR DESCRIPTION
**Pull request by mikebryant**
The engine is available at https://github.com/mikebryant/codeclimate-pylint
What's the process for getting it into the right docker registry?

### CODE REVIEW

**Comment by mgracer48** [comment]
:D

**Comment by mrb** [comment]
@mikebryant Hey Mike! Wow, nice! Can you shoot me an email at mrb@codeclimate.com? Thanks!

**Comment by pbrisbin** [comment]
@mrb were you able to sync up out of band? Can we close this issue?

**Comment by bittner** [comment]
What happened to this PR? This engine doesn't seem to be included in codeclimate by default today.

**Comment by maxjacobson** [comment]
@larkinscott might have more context than that ^

**Comment by larkinscott** [comment]
Hey @bittner! We have another version of this plugin (https://github.com/meuspedidos/codeclimate-pylint) that's in testing right now. It should be released to beta shortly.

**Pull request closed without merging**
