### PR TITLE
Alphabetize engines for easier addition going forward

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
@codeclimate/review @BlakeWilliams @jpignata In anticipation of adding new engines to manifest, this change orders engines already present in `engines.yml` manifest so that it is easier to read and modify going forward.

### CODE REVIEW

**Comment by ABaldwinHunter** [comment]
Interesting. The order in `engines.yml` affects the order in which engines are written to `.codeclimate.yml` during init. Is that intentional behavior? And/or do we want to decouple those things.

**Comment by GordonDiggs** [comment]
Probably consequential behavior but IMO not undesirable

**Comment by dblandin** [comment]
@ABaldwinHunter Yep. Ran into that in #174.

**Comment by ABaldwinHunter** [comment]
@dblandin Ah got it.

@GordonDiggs Hm I don't see a ton of benefit in maintaining an order in the generated config as the list of engines grows.

But I do see some value.

If we want that behavior, I like keeping the hierarchy knowledge somewhere else (or perhaps giving an ID or pecking order property to the engine).

Benefit: `engines.yml` is easier to navigate and only acts as a simple source of information

**Comment by ABaldwinHunter** [comment]
Wdyt? (I can also side step for now)

**Comment by ABaldwinHunter** [comment]
@GordonDiggs @dblandin Fixed tests. Ready for re-review!

**Comment by GordonDiggs** [comment]
LGTM

**Pull request merged**
