### PR TITLE
Add eslint-2 channel for eslint engine

### PR DESCRIPTION
**Pull request by pbrisbin**
/cc @codeclimate/review

I locally built and pushed an image from codeclimate/codeclimate-eslint#79 so
it's now available to try. Consider this a quiet release for wider testing,
it's entirely opt-in.

### CODE REVIEW

**Comment by abritinthebay** [comment]
Does this mean I can opt-in on a project *right now* if I edit my yml file?

**Comment by pbrisbin** [comment]
@abritinthebay yes, that's correct. Note that we're still testing this image out so I can't say for sure that it'll work, but you're welcome to try it:

Once you've updated to the latest CLI, you can add:

```yaml
eslint:
  enabled: true
  channel: eslint-2
```

**Comment by abritinthebay** [comment]
The latest CLI? Will it not also work on the web dashboard..?

**Comment by pbrisbin** [comment]
Oh yes sorry. Same caveat about it not being thoroughly tested yet, but you can commit that yaml change and it will run eslint on our hosted analysis too.

**Comment by abritinthebay** [comment]
hmmm I'm getting "We had trouble running the unknown engine."

Here's the engines section of my yml:

```
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: eslint-2
    config: .eslintrc.js
  fixme:
    enabled: true
  scss-lint:
    enabled: true
```

**Comment by pbrisbin** [comment]
Sorry, you were just a few minutes too soon as I was in the process of pushing that feature out for hosted analysis. It should work if you try again now.

**Comment by abritinthebay** [comment]
haha, what's more new that _bleeding edge_ ;) 

So right now it fails with `Error: Cannot find module 'estraverse-fb'

Which appears to be a babel-eslint dependency issue...?

**Comment by pbrisbin** [comment]
Damn. Unfortunately, I'm not immediately sure what the issue is there. I'll open up an issue on the engine repo to track it, but it probably won't get addressed today. Thank you very much for trying it out, and apologies that it's not working on your project yet.

**Comment by abritinthebay** [comment]
Worked it out but only you can fix it. For ESlint 2.x you need babel-eslint@6.x.x not the 5.x branch that works with regular ESlint.

**Comment by abritinthebay** [comment]
see here: https://github.com/babel/babel-eslint/issues/267

**Comment by abritinthebay** [comment]
I'm _very_ willing to alpha test this and find bugs - it's very important for my team here at Bleacher Report to get this in our toolchain on CC :)

**Comment by pbrisbin** [comment]
Thanks! I've rebuilt a new image from #92 with that fix and pushed it to Docker Hub, this means you could test the fix via the CLI right now. If you can only use hosted, you'll have wait just a bit longer as I go through the process of getting the image out there as well.

**Comment by abritinthebay** [comment]
I could use CLI locally but I'm totally willing to wait - don't have it fully set up to use the CLI atm.

**Comment by pbrisbin** [comment]
OK, that fix is now out. Feel free to try again.

**Comment by abritinthebay** [comment]
It works! 

I'm getting a lot of `Definition for rule 'babel/some-rule-name' was not found` which I guess means it's not loading the babel eslint plugin, but everything else seems to work.

This is great :) if that odd babel plugin issue starts working it'll be *perfect* !

**Comment by abritinthebay** [comment]
Specifically it seems to complain about `babel/no-await-in-loop`... but not the other babel rules we have in there... hmmm.

**Comment by abritinthebay** [comment]
for now I've just set that to not be checked in the `checks` section of the config.

**Comment by pbrisbin** [comment]
That's great to hear!

Tomorrow we'll be writing up documentation and dropping comments on all the OSS Issues where this support has been requested. Then we'll start collecting and addressing things like that. Thanks again for being an early tester (and finding that babel-eslint fix).

**Pull request merged**
