### PR TITLE
Delete temporary file after the engine has ran.

### PR DESCRIPTION
**Pull request by lucasmazza**
A possible fix for #245 e #246.

### CODE REVIEW

**Comment by GordonDiggs** [comment]
@lucasmazza here's the tricky bit about this (and why we initially went with a hardcoded path): The path within this `docker run` invocation must exist on the host machine as well (see where we mount it as a volume [here](https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper#L56)). So, I don't believe your current implementation will work, as `/tmp/foo` will exist within the `codeclimate` container, but not be accessible to the docker daemon, which is dropping back down to the host to mount the file.

**Comment by lucasmazza** [comment]
@GordonDiggs I have the image a proper spin locally and it failed - makes sense to delete the file after running the container instead?

**Comment by GordonDiggs** [comment]
@lucasmazza that would work too!

**Comment by lucasmazza** [comment]
@GordonDiggs rebased and updated the PR title with the delete approach.

**Comment by GordonDiggs** [comment]
LGTM. Thanks! Will merge on green

**Pull request merged**
