### PR TITLE
Support docker-machine with "default" migrated boot2docker

### PR DESCRIPTION
**Pull request by dbergey**
This PR fixes issue #86.

If the user has boot2docker installed and installs the Docker Toolbox, they are presented with the option to migrate boot2docker to a machine named 'default'.

This PR does not provide an option for a differently-named docker image, but I'm not sure it's needed.

### CODE REVIEW

**Comment by GordonDiggs** [comment]
@dbergey Thanks! Does this also work for people who start from scratch and install Docker Toolbox (rather than migrating from boot2docker)

**Comment by dbergey** [comment]
I'm not sure. I haven't had a chance to test on a fresh machine yet. I can do that soon, or someone else can try it out.

**Comment by brynary** [comment]
@dbergey can you please merge master into your branch? It should resolve the build failure

**Comment by kulte** [comment]
@dbergey I'm *very* new to Docker, can I pull the image from this PR before it gets merged/pushed to Docker registry server so I can roll with the new Docker Toolbox on my machine?

**Comment by ablyler** [comment]
@brynary looks like @dbergey did the merge. :+1:

**Comment by pbrisbin** [comment]
@kulte the following should work to try out this branch yourself:

```
git clone https://github.com/dbergey/codeclimate
cd codeclimate && sudo make install
```

This PR LGTM, but I still think we need an answer to Gordon's question before merging:

> Does this also work for people who start from scratch and install Docker Toolbox (rather than migrating from boot2docker)

**Comment by sveinn** [comment]
>"This PR LGTM, but I still think we need an answer to Gordon's question before merging:

>>Does this also work for people who start from scratch and install Docker Toolbox (rather than migrating from boot2docker)"

@pbrisbin I did not migrate from boot2docker and the following worked for me:

```
git clone https://github.com/dbergey/codeclimate
git checkout support-docker-machine
make install
codeclimate help
```

**Comment by pbrisbin** [comment]
Awesome, thanks @sveinn . I'll check with the team and hopefully merge/release this today.

**Comment by GordonDiggs** [comment]
Thank you! I will release this now

**Pull request merged**
