### PR TITLE
Add missing codeclimate-rubocop engine channels

### LINKED ISSUE #1031: Update rubocop engine channels
The config/engines.yml spec doesn't include all the engines in codeclimate-rubocop.

With an up to date codeclimate, running this command:
```
codeclimate engines:install
```
I get this warning:
```
WARNING: unknown engine <rubocop:rubocop-1-12-1>
```

Running `codeclimate analyze`, I get this warning:
```
Skipped rubocop: Channel rubocop-1-12-1 not found for rubocop, available channels: ["stable", "cache-support", "rubocop-0-42", "rubocop-0-46", "rubocop-0-48", "rubocop-0-49", "rubocop-0-50", "rubocop-0-51", "rubocop-0-52", "rubocop-0-54", "rubocop-0-55", "rubocop-0-56", "rubocop-0-57", "rubocop-0-58", "rubocop-0-59", "rubocop-0-60", "rubocop-0-61", "rubocop-0-62", "rubocop-0-63", "rubocop-0-64", "rubocop-0-65", "rubocop-0-66", "rubocop-0-67", "rubocop-0-68", "rubocop-0-69", "rubocop-0-70", "rubocop-0-71", "rubocop-0-72", "rubocop-0-73", "rubocop-0-74", "rubocop-0-75", "rubocop-0-76", "rubocop-0-76-airbnb", "rubocop-0-77", "rubocop-0-78", "rubocop-0-79", "rubocop-0-80", "rubocop-0-81", "rubocop-0-82", "rubocop-0-83", "rubocop-0-84", "rubocop-0-85", "rubocop-0-86", "rubocop-0-87", "rubocop-0-88", "rubocop-0-89", "rubocop-0-90", "rubocop-0-92", "rubocop-1-7-0", "rubocop-1-8-1", "rubocop-1-9-1"]
```

That list is a bit outdated. I'll make a PR.

### PR DESCRIPTION
**Pull request by BrianHawley**
[Fixes #1031] again

### CODE REVIEW

**Comment by BrianHawley** [comment]
@fede-moya here's the corresponding PR for rubocop 1.23.0

**Comment by fede-moya** [comment]
@BrianHawley I'm not sure if we want to release a new version of the CLI each time a new version of rubocop is out 😕  - Will discuss this internally and come back later.

**Comment by fede-moya** [comment]
we could use `beta` and always have `beta` pointing to rubocop's latest if you need to ? @BrianHawley

**Comment by BrianHawley** [comment]
I agree that there should be a better solution. Maybe something a bit less static, like grabbing the list of branches from codeclimate-rubocop and filtering to match a pattern?

In the long run, I don't really like the channel branch model, because most of the code is pretty much identical between branches, and because it makes it difficult to fix problems that exist in the integration code for multiple versions. The multiple version support could easily be done with the appraisal gem, and then just make the integration code work with multiple versions.

It does help to be able to specify a version, so we can match up the gem versions in a channel with the gem versions specified in our projects, so we can run the tools locally. However, a rubocop-latest channel with the latest version would be a good idea too, for people who just want to be able to use the latest versions.

**Comment by BrianHawley** [comment]
With the current channel model, you could create a channel/rubocop-latest branch based on channel/rubocop-1-23-0 and then add a rubocop-latest channel reference here. That would give you time to refactor before the next rubocop version comes out. When the next version comes out, channel/rubocop-latest can be updated.

**Comment by fede-moya** [comment]
I will make it `channel/beta` instead of `channel/rubocop-latest ` since around plugins `beta` means latest.

**Review by fede-moya — APPROVED** [review]

**Comment by BrianHawley** [comment]
@fede-moya could you reset channel/beta to the same commit as channel/rubocop-1-23-0? It's currently set to the channel/rubocop-1-22-3 commit.

**Comment by fede-moya** [comment]
@BrianHawley done

**Comment by BrianHawley** [comment]
@fede-moya https://github.com/codeclimate/codeclimate-rubocop/branches/all?query=channel%2F shows the channels, and channel/beta still matches channel/rubocop-1-22-3 - it needs to match channel/rubocop-1-23-0

**Comment by fede-moya** [comment]
@BrianHawley could you refresh and check again ?

**Comment by BrianHawley** [comment]
@fede-moya it's updated now, thanks!

**Comment by BrianHawley** [comment]
@fede-moya it still won't work with the CLI until you do at least one more release, including these changes. Then the beta channel can just be updated independently going forward.

**Pull request merged**
