### PR TITLE
Add rubocop 0-81

### PR DESCRIPTION
**Pull request by K-S-A**

### CODE REVIEW

**Comment by filipesperandio** [comment]
The channel already exists in [codeclimate-rubocop](https://github.com/codeclimate/codeclimate-rubocop/tree/channel/rubocop-0-81) but the upgrade itself still haven't been done, it is still at 0.80.1.

**Comment by K-S-A** [comment]
I see. @filipesperandio let me know if I can help you with an update to 0.80.1.

**Comment by filipesperandio** [comment]
something that helps is running [this](https://github.com/codeclimate/codeclimate-rubocop/blob/channel/rubocop-0-81/bin/newver) and opening a PR there with the changes. :D

**Comment by K-S-A** [comment]
Build passed for https://github.com/codeclimate/codeclimate-rubocop/pull/233

CC // @filipesperandio

**Comment by filipesperandio** [comment]
@K-S-A Cool! Thanks!
Merged the PR, it might take a while to be released but I will push it through!

**Comment by krzysiek1507** [comment]
I guess it can be merged?

**Comment by filipesperandio** [comment]
My bad. Doing it now.

**Comment by krzysiek1507** [comment]
Thank you!

**Pull request merged**
