### PR TITLE
Increase rubocop defaults for complexity checks

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Increase Class and Module length Max from 100 to 250

Turn on method length check
Increase method length Max from 10 to 80

- In light of grade point tuning
- leaves ABCSize enabled, Cyclomatic Complexity and Perceived Complexity disabled

@codeclimate/review

### CODE REVIEW

**Comment by pbrisbin** [comment]
These seem way too lenient to me, I think an 80 line method is
unacceptable, and 250 for a class is pretty bad.

I'm fine with it if these have already been discussed and decided in a
larger group, but if it's still up for discussion, I'd vote for limits of
150 and 15.

**Comment by wfleming** [comment]
I'm agree with @pbrisbin that these new numbers seem to large. What's the motivating issue here? I feel like the farther we stray from the underlying tool's defaults, the more potential confusion we cause for customers.

**Comment by ABaldwinHunter** [comment]
@wfleming @pbrisbin thanks. These were discussed and decided on. 

I'm fine with any changes though - nothing's set until set. cc @brynary 

Related point changes in codeclimate-rubocop: https://github.com/codeclimate/codeclimate-rubocop/pull/42

**Comment by ABaldwinHunter** [comment]
For some context / summary of discussion:

- Main motivation is to make scoring more similar to Classic
- These changes only impact the default .rubocop.yml generated during `init`
- The remediation points for complexity violations are steeper in the PR linked to above. Effectively, default is that users don't trigger the complexity violation until a higher threshold, but when they do, it's an automatic C.
- All complexity checks provided by Rubocop are included in our default config for informational purposes, but some are disabled. They're not necessarily meant to be used in conjunction with one another. Might create some redundant remediation scoring.

The Class and Method `length` checks seemed a more intuitive measure than `ABCSize` for beginners.

@brynary correct me on any of the above. :) 

cc @jpignata

**Comment by ABaldwinHunter** [comment]
@codeclimate/review Note: I had the method length incorrect. Should have been 30. Updated.  

cc @brynary

**Comment by wfleming** [comment]
30 seems much more reasonable than 80. :)

**Comment by brynary** [comment]
LGTM

**Pull request merged**
