### PR TITLE
Enable java duplication analysis by default for QM

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
We are already analyzing complexity for java by default on QM.

### CODE REVIEW

**Comment by wfleming** [comment]
Pretty sure this isn't actually used in QM and won't work. In fact I think this whole file might be defunct.

You want to modify `CC::Config::Default`.

**Comment by ABaldwinHunter** [comment]
> You want to modify CC::Config::Default.

@wfleming thanks! I think you're right - that's what's used for analysis.

However, this file appears to still be used - even in QM - for the `codeclimate engines:enable duplication` command.

So I think we want this change as well, right? Adding the other

**Comment by ABaldwinHunter** [comment]
@wfleming ready for another look!

**Comment by wfleming** [comment]
> However, this file appears to still be used - even in QM - for the codeclimate engines:enable duplication command.

Interesting. Well, having this in so many places is gonna be terrible long term, but that's a problem to consider another day.

**Pull request merged**
