### PR TITLE
add brakeman to manifest

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
@codeclimate/review @jpignata @mrb

### CODE REVIEW

**Comment by ABaldwinHunter** [comment]
Pushed onto docker hub

**Comment by ABaldwinHunter** [comment]
Weird. tests pass locally 
```CONSOLE
Ashleys-MacBook-Pro-2:codeclimate ashleybaldwin-hunter$ be rake

# Running tests with run options --seed 20076:
.......................................................................fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
.............................................................................

Finished tests in 6.460906s, 22.9070 tests/s, 61.2917 assertions/s.

148 tests, 396 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by pbrisbin** [comment]
Those specs could be flakey as they do docker-run and thread stuff. They're important specs, but anything that you can do to make them more stable would be worthwhile.

**Comment by ABaldwinHunter** [comment]
@pbrisbin cool, I'm making a card for that. Refreshed build and tests pass.

**Comment by jpignata** [comment]
:ship: :ship: :ship:

**Comment by ABaldwinHunter** [comment]
@jpignata Thanks!

**Pull request merged**
