### PR TITLE
Added env var for image prefix to engine registry

### PR DESCRIPTION
**Pull request by sololegends**
# Changes
Added environmen variable CODECLIMATE_PREFIX as an option for the codeclimate analyzer image prefix. 

This will allow offline code quality scanning something huge for many orginazations

# Impact
These changes won't impact any existing configurations. Anyone wanting to use this feature can , but no one will have to alter their environments to use a new image. 

# Testing
- Tested pointing to a local docker registry (GOOD)
- Tested swapping the codeclimate image in an environment already using codeclimate:0.85.8 (GOOD)
   - No changes required for functionality
- Tested swapping the codeclimate image in an environment already using codeclimate:0.85.9 (GOOD)
   - No changes required for functionality

### CODE REVIEW

**Comment by goldenson** [comment]
👋 @filipesperandio should we merge this MR as it has been approved?

**Comment by filipesperandio** [comment]
My bad.
Got distracted and forgot to come back here.

**Comment by HSKC** [comment]
Thanks man. You saved my day. Someone should add this to the documentation.

**Comment by trulyliu** [comment]
Any usage example?

**Comment by sololegends** [comment]
> Any usage example?

I use it in my gitlab CI scripts, https://gitlab.sololegends.com/gitlab/offline-gitlab   

Also, I've implemented this in the gitlab code quality scanner: https://gitlab.com/gitlab-org/ci-cd/codequality/-/blob/master/run.sh

Otherwise, just add the env variable "CODECLIMATE_PREFIX" to the docker run command.
I. E. 
`docker run -env CODECLIMATE_PREFIX=repo.example.com --volume "$SOURCE_CODE":/code codeclimate/codeclimate analyze`

**Pull request merged**
