### PR TITLE
Run engine as app user

### PR DESCRIPTION
**Pull request by GordonDiggs**
/cc @codeclimate/review 

This runs engines as `app` instead of `root`.

**NOTE: Do not merge this until all the engines are updated:**

- bundler-audit: https://github.com/codeclimate/codeclimate-bundler-audit/pull/2
- coffeelint: https://github.com/codeclimate/codeclimate-coffeelint/pull/1
- csslint: https://github.com/codeclimate/codeclimate-csslint/pull/3
- eslint: https://github.com/codeclimate/codeclimate-eslint/pull/11
- gofmt: https://github.com/codeclimate-community/codeclimate-gofmt/pull/1
- golint: https://github.com/codeclimate-community/codeclimate-golint/pull/1
- govet: https://github.com/codeclimate-community/codeclimate-govet/pull/1
- phpcodesniffer: https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/6
- rubocop: https://github.com/codeclimate/codeclimate-rubocop/pull/2
- rubymotion: https://github.com/HipByte/codeclimate-rubymotion/pull/1
- watson: https://github.com/codeclimate-community/codeclimate-watson/pull/1

### CODE REVIEW

**Comment by pbrisbin** [comment]
What happens if you do run this with an engine that doesn't have an `app` user? When we were debugging the `codeclimate.yml` permissions issue, we were able to run as a user *id* that didn't exist in the engine and (as long as we didn't do something that required actual permissions) it didn't seems to blow up.

**Comment by GordonDiggs** [comment]
@pbrisbin the analysis errors out:

```
~/git_repos/ellis (master) 🐖  codeclimate analyze
Starting analysis
Running eslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr "Unable to find user app\ntime=\"2015-06-26T14:23:50Z\" level=fatal msg=\"Error response from daemon: Cannot start container 6241cbf968dc5e1041cd4a48bd967d5171cbd6008ab0e0509d48af28df0aedcd: [8] System error: Unable to find user app\" \n"
```

**Comment by pbrisbin** [comment]
And what about `--user 9000`?

**Comment by GordonDiggs** [comment]
@pbrisbin hmmm that does run - how do we handle that? Seems like using `app` here gets around that problem

**Comment by pbrisbin** [comment]
I think that using `--user 9000` is nicer to engine authors:

- You're not running as root, our only goal here
- If the engine follows the spec, 9000 == app, and the engine could use that in whatever way it wants
- If the user doesn't exist, you're basically running as no one; you can't create files and you can't access resources not available to the "everyone" bit -- aka exactly what we'd want

I'm not sure I see a downside.

/cc @brynary

**Comment by GordonDiggs** [comment]
@pbrisbin read up a bit and addressed the issue - using UID and GID now

**Pull request merged**
