### PR TITLE
Output test results in JUnit XML for CircleCI

### PR DESCRIPTION
**Pull request by sgerrand**
💁  These changes add an extra output format for tests to enable CircleCI to consume them.

> CircleCI can collect test metadata from JUnit XML files and Cucumber JSON
> files. We’ll use the test metadata to give you better insight into your build.
> For our inferred steps that use parallelism, we’ll use the timing information
> to get you better test splits and finish your builds faster.

https://circleci.com/docs/test-metadata/

### CODE REVIEW

**Comment by pbrisbin** [comment]
I think you've made this PR against a very old version of master. We've actually moved from minitest to rspec since then. In any event, I don't think we're interested in using this aspect of Circle for this project.

**Comment by sgerrand** [comment]
> I think you've made this PR against a very old version of master. We've actually moved from minitest to rspec since then. In any event, I don't think we're interested in using this aspect of Circle for this project.

I did. :blush:

Subsequently updated to tie into the Docker, make and RSpec changes. ✨

**Comment by sgerrand** [comment]
🎉  
output with JUnit XML

**Comment by sgerrand** [comment]
> In any event, I don't think we're interested in using this aspect of Circle for this project.

Really? Oh well, feel free to close this once you confirm that decision. 😞

**Comment by pbrisbin** [comment]
I spoke with the team and while there wasn't too much excitement either way, this doesn't really hurt anything so why not try it out? If you go ahead and rebase one more time (sorry), I'll merge it in.

**Comment by sgerrand** [comment]
😅  Rebased in c8a1539. ♻️

**Pull request merged**
