### PR TITLE
Update default .rubocop.yml for 0.47.1

### PR DESCRIPTION
**Pull request by maxjacobson**
These cops were renamed/moved

### CODE REVIEW

**Comment by pbrisbin** [comment]
@maxjacobson is there anything blocking this from merge?

**Comment by maxjacobson** [comment]
@pbrisbin yes. The codeclimate-rubocop engine is currently running rubocop 0.46.0. I'm planning to spend some time this week upgrading the codeclimate-rubocop engine from 0.46 to 0.47.1, after which we can ship this. I'd like to find a way to do it that tolerates outdated configuration more gracefully

**Comment by pbrisbin** [comment]
Sounds good. This is further evidence that a better default-config system would allow the engines to themselves control what default configs are written for them.

**Comment by jhabdas** [comment]
Update?

**Comment by maxjacobson** [comment]
Update: we've added a channel to support RuboCop 0.48.1. We haven't switched to making it the default yet, but users can opt in by following the steps here: https://docs.codeclimate.com/docs/rubocop#section-using-rubocop-s-newer-versions

Thanks for the ping. Going to close this PR for now. We'll open a similar one when we change the default.

**Pull request closed without merging**
