### PR TITLE
Release v0.85.23

### PR DESCRIPTION
**Pull request by fede-moya**

### CODE REVIEW

**Comment by filipesperandio** [comment]
@fede-moya Have you created this PR by running `bin/prepare-release 0.85.23` by any chance?

**Comment by fede-moya** [comment]
> @fede-moya Have you created this PR by running `bin/prep-release 0.85.23` by any chance? Or through manual steps?

@filipesperandio created with `bin/prep-release 0.85.23`

**Comment by filipesperandio** [comment]
Cool, yeah. If you have `hub` CLI installed it also creates the PR and adds the commits diff in the description which is a nice 💄 
(like on this one: https://github.com/codeclimate/codeclimate/pull/1002#issue-560152033)


https://github.com/github/hub

**Review by filipesperandio — APPROVED** [review]

**Comment by fede-moya** [comment]
@filipesperandio Thanks for approving but it's not that I didn't hear your suggestion of using `hub` for creating the release but that the fix that I have merged for stylelint's has not been optimal. I have another update on the way so I'll delay this release until we have that other update. Also, I have already installed `hub` thanks for suggesting that.

**Pull request merged**
