### PR TITLE
Upgrade to Ruby 2.6.6

### PR DESCRIPTION
**Pull request by artfuldodger**
Specs start failing with 2.7.1.

### CODE REVIEW

**Review by filipesperandio — COMMENTED** [review]
I think this move should account for a couple other things too.
For ref: https://github.com/codeclimate/codeclimate/commit/ac66e5a9b0abaed38ef384897c7d154a3b79f4e2

**Comment by artfuldodger** [comment]
Ah yup, thanks for the reference commit @filipesperandio! PR is updated.

**Review by filipesperandio — COMMENTED** [review]
Thanks!
Mind checking the violations too?
https://codeclimate.com/github/codeclimate/codeclimate/pull/987

I also wouldn't mind if we update rubocop to a more recent version. (rubocop-0-92)
https://github.com/codeclimate/codeclimate/blob/master/.codeclimate.yml#L10

**Comment by artfuldodger** [comment]
Fixed the violations, upgraded Rubocop, and addressed the new violations as well. :)

**Review by filipesperandio — APPROVED** [review]

**Comment by filipesperandio** [comment]
@artfuldodger  Sorry this took me that long! Thanks for the contribution.

**Pull request merged**
