### PR TITLE
enable bundler-audit when Gemfile.lock present

### PR DESCRIPTION
**Pull request by wfleming**
Looks like this was using the wrong yaml key: I don't see any reference
to `enable_patterns` in the code.

### CODE REVIEW

**Comment by pbrisbin** [comment]
LGTM, is there a good way to confirm this works? I assume there's no good way to get it into the test suite.

**Comment by wfleming** [comment]
@pbrisbin I'll alter the tests for it, but since I can't foresee that merging at all cleanly with #137, I'm going to wait until that's done & then I'll rebase this & update it. Make sense?

**Comment by pbrisbin** [comment]
Fine with me, although I don't see a merge conflict on the horizon.

**Comment by wfleming** [comment]
@pbrisbin spec added.

**Comment by pbrisbin** [comment]
Awesome. LGTM

**Pull request merged**
