### PR TITLE
Add nil check

### PR DESCRIPTION
**Pull request by maxjacobson**
I hit a NoMethodError while running what turns out to be a nonsense
command: `codeclimate help --no-check-version`

### CODE REVIEW

**Comment by dblandin** [comment]
While you're in here, I'm also getting an error when running `codeclimate` with no args:

```
$ CODECLIMATE_DEBUG=1 codeclimate
error: (NoMethodError) undefined method `any?' for nil:NilClass
[DEBUG] backtrace: /usr/src/app/lib/cc/cli/help.rb:14:in `run'
        /usr/src/app/lib/cc/cli/command.rb:70:in `execute'
        /usr/src/app/lib/cc/cli/runner.rb:22:in `run'
        /usr/src/app/lib/cc/cli/runner.rb:8:in `run'
        /usr/src/app/bin/codeclimate:6:in `<main>'
```

Also tests?

**Comment by maxjacobson** [comment]
Ah good catch. I'll add a spec for this one first and then take a look at that one in a second PR

**Comment by maxjacobson** [comment]
@dblandin  updated, and opened https://github.com/codeclimate/codeclimate/pull/596

**Comment by maxjacobson** [comment]
@dblandin LGTY?

**Comment by dblandin** [comment]
Yep! LGTM. Love that green! :ok_hand:

2017-03-16-164645_1004x324_scrot

**Pull request merged**
